### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by iah**
First batch of translation strings.

### CODE REVIEW

**Comment by DHM47** [comment]
Thank you

**Comment by DHM47** [comment]
What would you like the name in the credits to be ?

**Comment by iah** [comment]
Hi,

Isak Alexander as name. Isak@kajko.se

Thanks!

Best regards,


Isak Holmström
isak@iah.io [isak@iah.io]
0705 / 32 38 20

On Fri, Mar 11, 2016 at 8:06 p.m., DHM47 < notifications@github.com [notifications@github.com] > wrote:
What would you like the name in the credits to be ?

—
Reply to this email directly or view it on GitHub
[https://github.com/DHM47/Native-Clip-Board/pull/66#issuecomment-195501193] .[https://github.com/notifications/beacon/AAH8ZYEXl6HEjmnh_w1c3nuXxNMA03fXks5psb0bgaJpZM4HobTW.gif]

**Comment by DHM47** [comment]
I will added the name to the credits,
And if you want I'll email you whenever I add anything that needs to be translated. Would you want that ?

**Comment by iah** [comment]
Absolutely, thanks!

Best regards,


Isak Holmström
isak@iah.io [isak@iah.io]
0705 / 32 38 20

On Fri, Mar 11, 2016 at 8:12 p.m., DHM47 < notifications@github.com [notifications@github.com] > wrote:
I will added the name to the credits,
And if you want I'll email you whenever I add anything that needs to be
translated. Would you want that ?

—
Reply to this email directly or view it on GitHub
[https://github.com/DHM47/Native-Clip-Board/pull/66#issuecomment-195503585] .[https://github.com/notifications/beacon/AAH8ZYu7PyJMbO1HgDG_sIAtfJfHRm1tks5psb6QgaJpZM4HobTW.gif]

**Pull request merged**
