### PR TITLE
Final color changes

### PR DESCRIPTION
**Pull request by asdfasdfvful**
Should have everything covered. Not sure what is controlling the text in the about section so I'll assume it'll all be in styles.

### CODE REVIEW

**Comment by DHM47** [comment]
Those a colors are in the html file 
https://github.com/DHM47/Native-Clip-Board/blob/master/assets/html/about.html 
Also this is a Web page, I'm not sure you can change it.

**Comment by DHM47** [comment]
https://www.dropbox.com/s/jiwd8ii657c8c4r/NativeClipBoard3.2.1-ThemeingTest2.apk?dl=0

If something else is not getting themed correctly tell me.

**Comment by asdfasdfvful** [comment]
Thanks! Everything is working well :). I'll push it to my theme once you update your build in the xposed download section.

screenshot_2015-05-17-13-35-30

**Comment by DHM47** [comment]
Update released

**Pull request merged**
