### PR TITLE
String update and bold

### PR DESCRIPTION
**Pull request by HankAviator**
`<![CDATA[<b></b>]]>` is superb!

### CODE REVIEW

**Comment by DHM47** [comment]
Why is it showing so much changes even though nothing seems to have changed aside from bold?

**Comment by HankAviator** [comment]
It has been a while since I last translated for you. The structure of English strings has diverged and I followed up by moving some lines in sync.

**Comment by DHM47** [comment]
Oh, also I added a few strings. Please translate them.

**Comment by HankAviator** [comment]
Opened a new PR

**Pull request merged**
