### PR TITLE
zh-rCN update

### PR DESCRIPTION
**Pull request by HankAviator**
Note there's no capital characters in Chinese, suggesting **Bold** to emphasize.

### CODE REVIEW

**Comment by HankAviator** [comment]
Incremental update to match upstream changes.  Note there's no capital characters in Chinese, suggesting **Bold** to emphasize.

**Comment by DHM47** [comment]
Which part exactly represents the capital word in English ?

**Comment by HankAviator** [comment]
“... will be REPLACED" @DHM47

**Comment by DHM47** [comment]
Yeah, but which one is it in Chinese?

**Comment by HankAviator** [comment]
”...都会被**覆盖**“

**Comment by DHM47** [comment]
This is how it looks, so translate it and put what needs to be bold in place of the xxxx 
<![CDATA[<b>xxxx</b>]]>

<string name="chrome_warning">Due to limitations in Chrome when pasting a clip <![CDATA[<b>all</b>]]> previous text in the field will be <![CDATA[<b>replaced</b>]]> </string>

**Comment by DHM47** [comment]
github, changed the text, I'll update the string file and you should understand it

**Pull request merged**
