### PR TITLE
Update color.xml

### PR DESCRIPTION
**Pull request by asdfasdfvful**

### CODE REVIEW

**Comment by asdfasdfvful** [comment]
Sorry, I accidentally made all my commits on your repo so all the requests are separate. If you add this, could you please also add
    <color name="clipboard_preference_bg">#ffeeeeee</color>

to the file? This will essentially make the app themable for the cm theme chooser

**Comment by DHM47** [comment]
No problem, what should it be named ? 
This is quit interesting, you are a themer as I remember. So after I merge the changes I'll send you an apk to test. OK?

**Comment by DHM47** [comment]
I found what ffeeeeee should be named.
Here is the apk :
https://www.dropbox.com/s/xrqoygy873fh5tl/NativeClipBoard3.2.1-ThemeingTest.apk?dl=0
Can you send me a screenshot of the results ?

**Comment by asdfasdfvful** [comment]
Sorry on my phone now so I accidentally pressed some things. Essentially, the app looks the same without modifications, but I'll be able to theme it since I moved the colors to where I can edit them. I'll send you a screenshot once it is themed.

**Comment by DHM47** [comment]
Looking forward to it. :+1:

**Pull request merged**
